server:
  port: 10003

spring:
  profiles:
    active: dev
  application:
    name: anyway-boot-admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  security:
    user:
      name: "admin"
      password: "admin"

eureka:
  instance:
    metadata-map:
      user.name: "admin"
      user.password: "admin"
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

---

spring:
  profiles: test

---

spring:
  profiles: prod
