server:
  port: 10001

spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway-${spring.profiles.active}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

---

spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
