server:
  port: 12000

spring:
  profiles:
    active: dev
  application:
    name: anyway-config

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaozi0513/anyway.git
          search-paths: config-repo
    bus:
      enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092
#    consumer:
#      group-id: config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka


