server:
  port: 12000

spring:
  application:
    name: anyway-config
  cloud:
    config:
      server:
        git:
          uri: http://github.com/xiaozi0513/anyway
          search-paths: config-repo
    bus:
      enabled: true
      trace:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
